### ISSUE TITLE
Can we use `disc_union` in production?

### ISSUE THREAD

**Issue by bySabi** [X4lldux/disc_union#4]
We are planning to use on a DDD Elixir project.  Any feedback on is really welcome.

**Comment by X4lldux** [comment]
> Can we use `disc_union` in production?

Yes! I'm already using current master (disc_union@2f305d3a8e53e7a1315c02cd2d1ff6fb0ce6cd2a) in production. I was stalling until #3 was resolved, but lately I'm thinking I'll just leave it hanging for now (some input will be very much appreciated) and make a new release any day now.


> We are planning to use on a DDD Elixir project.

Funny you should mentioned that, because I'm building a CQRS+ES library for my company and `disc_union` is heavily used there - commands and events must be discriminated unions. In our project,  that is using that library, I also use tagged unions for defining possible errors each command can return.
That library is not open sourced yet, but if you'd like to talk about it privately just email me or send a message on elixir slack.

**Comment by bySabi** [comment]
@X4lldux I send you two mails. Maybe is on spam folder.
